name: James Robertson Loft
favicon: null
layout_spectrum: 0.48305
typography_spectrum: 0.5191
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: James Loft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74062769-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#463d40'
    - '#0f0e13'
    - '#7e807f'
    - '#baa499'
    - '#bc6730'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
