name: James Robertson Loft
favicon: null
layout_spectrum: 0.51604
typography_spectrum: 0.5356301018036902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bbbbbb'
    - '#5d5d5d'
    - '#808080'
    - '#3e3e3e'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
